#!/usr/bin/env bash

# shellcheck disable=SC2155 # Declare and assign separately to avoid masking return values.

readonly SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
readonly PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
readonly BASH_LIBS_DIR="$PROJECT_ROOT/lib"

# shellcheck source=../lib/result_type_lib.bash
source "$BASH_LIBS_DIR/result_type_lib.bash" || exit 1
# shellcheck source=../lib/fsa_lib.bash
source "$BASH_LIBS_DIR/fsa_lib.bash" || exit 1
# shellcheck source=../lib/command_line_lib.bash
source "$BASH_LIBS_DIR/command_line_lib.bash" || exit 1

show_help() {
    local command_name="${1##*/}"

    cat <<EOF
Usage:
  $command_name <file-system> <archive-directory> [OPTIONS]

Description:
  Create an fsa archive of the <file-system> partition,
  saving it in <archive-directory>.

Arguments:
  <file-system>
      Label of the source partition to be archived.

  <archive-directory>
      Directory where the archive will be saved.

Options:
  --help
      Show this help message and exit.

EOF
}

#
# archive-file-system <file-system> <archive-directory> [OPTIONS]
#
error_trace=""

getopt_spec="help"

if ! register_command_line error_trace "$getopt_spec" "$@"; then
    print_error_trace "$error_trace"
    exit 1
fi

if has_command_line_opt "help"; then
    show_help "$0"
    exit 0
fi

declare -i arg_count

get_command_line_arg_count arg_count

if [[ arg_count -ne 2 ]]; then
    show_help "$0"
    exit 2
fi

declare file_system archive_directory result

get_command_line_arg 1 file_system
get_command_line_arg 2 archive_directory

printf_stderr 'Archiving "%s" to "%s".\n' "$file_system" "$archive_directory"

if ! archive_file_system result "$file_system" "$archive_directory"; then
    print_error_trace "$result"
    exit 1
fi

fsa_file="$result"

printf_stderr '"%s" created.\n' "$fsa_file"

if ! fsarchiver_archinfo result "$fsa_file"; then
    print_error_trace "$result"
    exit 1
fi

exit 0
