#!/usr/bin/env bash

# shellcheck disable=SC2155 # Declare and assign separately to avoid masking return values.
# shellcheck disable=SC2181 # Check exit code directly with e.g. `if mycmd;`, not indirectly with `$?`.

readonly SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
readonly PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
readonly BASH_LIBS_DIR="$PROJECT_ROOT/lib"

# shellcheck source=../lib/result_type_lib.bash
source "$BASH_LIBS_DIR/result_type_lib.bash"
(($? == 0)) || exit 1

# shellcheck source=../lib/fsa_lib.bash
source "$BASH_LIBS_DIR/fsa_lib.bash"
(($? == 0)) || exit 1

# shellcheck source=../lib/command_line_lib.bash
source "$BASH_LIBS_DIR/command_line_lib.bash"
(($? == 0)) || exit 1

show_help() {
    local command_name="${1##*/}"

    cat <<EOF
Usage:
  $command_name <file-system> <rspec> [OPTIONS]

Description:
  Create an fsa archive of the <file-system> partition,
  saving it in <rspec>.

Arguments:
  <file-system>
      Label of the source partition to be archived.

  <rspec>
      Resource-spec where the archive will be saved.

Options:
  --help
      Show this help message and exit.

EOF
}

#
# archive-file-system <file-system> <rspec> [OPTIONS]
#
error_trace=""

getopt_spec="help"

register_command_line error_trace "$getopt_spec" "$@" || {
    print_error_trace "$error_trace"
    exit 1
}

if has_command_line_opt "help"; then
    show_help "$0"
    exit 0
fi

declare -i arg_count

get_command_line_arg_count arg_count

if [[ arg_count -ne 2 ]]; then
    show_help "$0"
    exit 2
fi

declare file_system unvalidated_rspec rspec

get_command_line_arg 1 file_system
get_command_line_arg 2 unvalidated_rspec

rspec_validate rspec "$unvalidated_rspec" || {
    print_error_trace "$rspec"
    exit 1
}

printf_stderr 'Archiving "%s" to "%s" ...\n' "$file_system" "$(rspec_format "$rspec")"

declare fsa_file

archive_file_system fsa_file "$file_system" "$rspec" || {
    print_error_trace "$fsa_file"
    exit 1
}

printf_stderr '... "%s" created.\n' "$fsa_file"
exit 0
