#!/usr/bin/env bash

# shellcheck disable=SC2155 # Declare and assign separately to avoid masking return values.
# shellcheck disable=SC2181 # Check exit code directly with e.g. `if mycmd;`, not indirectly with `$?`.
readonly SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
readonly PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
readonly BASH_LIBS_DIR="$PROJECT_ROOT/lib"

# shellcheck source=../lib/command_line_lib.bash
source "$BASH_LIBS_DIR/command_line_lib.bash"
(($? == 0)) || exit 1

# shellcheck source=../lib/result_type_lib.bash
source "$BASH_LIBS_DIR/result_type_lib.bash"
(($? == 0)) || exit 1

# shellcheck source=../lib/rspec_lib.bash
source "$BASH_LIBS_DIR/rspec_lib.bash"
(($? == 0)) || exit 1

# shellcheck source=../lib/sync_lib.bash
source "$BASH_LIBS_DIR/sync_lib.bash"
(($? == 0)) || exit 1

show_help() {
    local command_name="${1##*/}"

    cat <<EOF
Usage:
  $command_name <user> <directory> <rspec> [OPTIONS]

Options:
  --help
      Show this help message and exit.

  --dry-run
      Run sync as a dry run.

EOF
}

#
# sync-user-directory <user> <directory> <rspec> [OPTIONS]
#
error_trace=""

getopt_spec="help,dry-run"

register_command_line error_trace "$getopt_spec" "$@" || {
    print_error_trace "$error_trace"
    exit 1
}

if has_command_line_opt "help"; then
    show_help "$0"
    exit 0
fi

declare -i arg_count

get_command_line_arg_count arg_count

if [[ arg_count -ne 3 ]]; then
    show_help "$0"
    exit 2
fi

declare user directory raw_rspec

get_command_line_arg 1 user
get_command_line_arg 2 directory
get_command_line_arg 3 raw_rspec

declare rspec

rspec_normalize rspec "$raw_rspec" || {
    print_error_trace "$rspec"
    exit 1
}

has_command_line_opt "dry-run"
declare is_dry_run="$?"

sync_user_directory error_trace "$user" "$directory" "$rspec" "$is_dry_run" || {
    print_error_trace "$error_trace"
    exit 1
}

exit 0
